In [1]:
# Jupyter magic
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt  # standard Python plotting library

# import the tdt library
import tdt
import pandas as pd
from numpy import genfromtxt

In [2]:
def combine_bouts(array, threshold):
    combined = [array[0]]
    for i in range(1, len(array)):
        if array[i] - combined[-1] > threshold:
            combined.append(array[i])
    return np.array(combined)

def combine_bouts_end(array, threshold):
    combined = [array[0]]
    for i in range(1, len(array)):
        if array[i] - combined[-1] > threshold:
            combined[-1] = array[i-1]
            combined.append(array[i])
    combined[-1] = array[-1]  # Ensure the last point is included
    return np.array(combined)

In [19]:
# Must read with "/" not "\
onset_Path= r"C:\Users\yongc\Desktop\Exp 2 - 03032024 Social Defeat 2\Adjusted Videos\mPFC Agonistic Behavior Onset.csv"
offset_Path= r"C:\Users\yongc\Desktop\Exp 2 - 03032024 Social Defeat 2\Adjusted Videos\mPFC Agonistic Behavior Offset.csv"

In [20]:
onset_list = genfromtxt(onset_Path, delimiter=',')
offset_list = genfromtxt(offset_Path, delimiter=',')
onset_list

array([    nan, 235.348, 238.745, 243.293, 245.826, 286.126, 396.143,
       422.28 ])

In [21]:
onset_list = onset_list[1:]
offset_list = offset_list[1:]
onset_list

array([235.348, 238.745, 243.293, 245.826, 286.126, 396.143, 422.28 ])

In [22]:
onset_list = combine_bouts(onset_list, 7)
offset_list = combine_bouts_end(offset_list, 7)
onset_list

array([235.348, 243.293, 286.126, 396.143, 422.28 ])

In [23]:
onset_df = pd.DataFrame(onset_list, columns=['timestamps'])
offset_df= pd.DataFrame(offset_list, columns=['timestamps'])

In [24]:
onset_df.to_csv (r'C:\Users\yongc\Desktop\Exp 2 - 03032024 Social Defeat 2\Adjusted Videos\mPFC_Agbeh_onset_df_correct.csv', index = None)
offset_df.to_csv (r'C:\Users\yongc\Desktop\Exp 2 - 03032024 Social Defeat 2\Adjusted Videos\mPFC_Agbeh_offset_df_correct.csv', index = None)